export default {
  displayLarge: {
    fontFamily: 'Celias-Regular',
    fontWeight: '400',
    fontSize: 57,
    lineHeight: 64,
  },
  displayMedium: {
    fontFamily: 'Celias-Regular',
    fontWeight: '400',
    fontSize: 45,
    lineHeight: 52,
  },
  displaySmall: {
    fontFamily: 'Celias-Regular',
    fontWeight: '400',
    fontSize: 36,
    lineHeight: 44,
  },
  headlineLarge: {
    fontFamily: 'Celias-Bold',
    fontWeight: '600',
    fontSize: 32,
    lineHeight: 40,
  },
  headlineMedium: {
    fontFamily: 'Celias-Bold',
    fontWeight: '600',
    fontSize: 28,
    lineHeight: 36,
  },
  headlineSmall: {
    fontFamily: 'Celias-Bold',
    fontWeight: '600',
    fontSize: 24,
    lineHeight: 32,
  },
  titleLarge: {
    fontFamily: 'Celias-Bold',
    fontWeight: '600',
    fontSize: 22,
    lineHeight: 28,
  },
  titleMedium: {
    fontFamily: 'Celias-Bold',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
  },
  titleSmall: {
    fontFamily: 'Celias-Bold',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 20,
  },
  bodyLarge: {
    fontFamily: 'Celias-Regular',
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 24,
  },
  bodyMedium: {
    fontFamily: 'Celias-Regular',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 20,
  },
  bodySmall: {
    fontFamily: 'Celias-Regular',
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
  },
  labelLargeProminent: {
    fontFamily: 'Celias-Bold',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 20,
  },
  labelLarge: {
    fontFamily: 'Celias-Medium',
    fontWeight: '500',
    fontSize: 14,
    lineHeight: 20,
  },
  labelMediumProminent: {
    fontFamily: 'Celias-Bold',
    fontWeight: '600',
    fontSize: 12,
    lineHeight: 16,
  },
  labelMedium: {
    fontFamily: 'Celias-Medium',
    fontWeight: '500',
    fontSize: 12,
    lineHeight: 16,
  },
  labelSmallProminent: {
    fontFamily: 'Celias-Bold',
    fontWeight: '600',
    fontSize: 11,
    lineHeight: 16,
  },
  labelSmall: {
    fontFamily: 'Celias-Regular',
    fontWeight: '400',
    fontSize: 11,
    lineHeight: 16,
  },
} as const;
